import Head from 'next/head'

import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Results from '../components/Results'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>IMDB Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* HEADER */}
      <Header />

      {/* NAVBAR */}
      <Navbar />

      {/* RESULTS */}
      <Results />
      
    </div>
  )
}
